export const defaultJSON = `{ 
  "width": 300,
  "showRomanNumbers": false,
  "showMinuteScale": true,
  "showHourScale": true,
  "showNumbers": true,
  "radialDirectionOfNumbers": false,
  "showOuterRing": true,
  "showInnerRing": true,
  "colorOfScalesAndNumbers": "black",
  "hourHandColor": "#151515",
  "minuteHandColor": "black",
  "secondHandColor": "red",
  "firstCircleColor": "white",
  "secondCircleColor": "white",
  "thirdCircleColor": "white",
  "fourthCircleColor": "black",
  "centerDotColor": "black",
  "numberSize": 150,
  "iana": "Europe/London"
}`;